### ISSUE TITLE
밋업 생성시 datetime 필드 대신에 date와 time 구분된 splitdatetime으로 변경

### ISSUE THREAD

**Issue by kyunooh** [milooy/hobbycoding#37]
현재 datetime 필드는 브라우저에서 제대로 지원하지 않네요 ㅠㅠ + 이 이슈는 이제 제 것입니다

**Comment by kyunooh** [comment]
낚였습니다... bower 통해서 패키지 다 인스톨하니까 잘 되네요 흠흠 깊은 반성과 함께 셀프 클로즈합니다.

**Comment by milooy** [comment]
ㅋㅋㅋㅋㅋㅋㅋ
셀프 클로즈...
